[package]
name = "scorsese-providers"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
scorsese-core = { version = "0.1.0", path = "../core" }
scorsese-zimmer = { version = "0.1.0", path = "../zimmer" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.19"
ureq = { version = "3.3.0", default-features = false, features = ["json", "rustls"] }
